CREATE TABLE CUST_DETAILS (ACC_NO INT, ACC_TYPE VARCHAR(10), NAME VARCHAR(10),ADDRESS VARCHAR(10), BALANCE VARCHAR(10)); INSERT INTO CUST_DETAILS VALUES (1001, 'SAVING','SUJITH','KASARAGOD',20000);
 INSERT INTO CUST_DETAILS VALUES (1002, 'SAVING','SAM','KANNUR',30000);
INSERT INTO CUST_DETAILS VALUES (1003, 'CURRENT','SREE','CALICUT',40000);
INSERT INTO CUST_DETAILS VALUES (2001, 'LOAN','LOANOFSAM','KANNUR',0);
INSERT INTO CUST_DETAILS VALUES (2002, 'LOAN','LOANOFSUJ','KASARAGOD',0);
SELECT * FROM CUST_DETAILS;
 SET AUTOCOMMIT=0
    -> INSERT INTO CUST_DETAILS VALUES(2005,'SAVING','DEV','KANNUR',10000)
    -> ROLLBACK;
